---
- hosts: all
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:
    - name: check uptime
      command: uptime
      register: uptime_output
    - name: create user
      user:
        name: claudius1
        state: present
        comment: "Claudius1 Joel"

      when: uptime_output.changed == false
      tags: 
        - create_user
    - name: print uptime
      debug:
        var: uptime_output.stdout